### PR TITLE
Process photos using a queue and workers

### LINKED ISSUE #1073: Need photo add queue
After some testing over the weekend traveling (and taking lots of photos), I'm seeing that the app crashes when trying to process many photo adds. 

We "prepare" the photos (`prepareFiles` call) using a go routine internally (background thread), so I think all the prepares are running simultaneously. I'm guessing this uses a lot of memory and the app is being killed because it's using too much memory. This is especially bad when it happens during a background fetch session because, on iOS, the background fetch completion handler is never called and iOS penalizes the app by reducing the number of future background fetch sessions.

### PR DESCRIPTION
**Pull request by asutula**
We want some control over how concurrency is used to process camera roll photos, adding them to the local Textile node. This allows us to balance speed and memory consumption. 

Closes #1073

### CODE REVIEW

File: App/features/photos/actions.ts [hunk 1]
```diff
@@ -12,6 +12,10 @@ export const updateLastQueriedTime = createAction('photos/UPDATE_LAST_QUERIED_TI
   return (epochSeconds: number) => resolve({ epochSeconds })
 })
 
+export const photoProcessingBegan = createAction('photo/PHOTO_PROCESSING_BEGAN', (resolve) => {
+  return (id: string) => resolve({ id })
+})
```
Comment (asutula) [inline App/features/photos/actions.ts]: This action is used to move the photo from `pending` to `preparing` state

File: App/features/photos/reducer.ts [hunk 2]
```diff
@@ -46,9 +46,15 @@ export default combineReducers<PhotosState, PhotosAction>({
     switch (action.type) {
       case getType(actions.queryCameraRoll.success): {
         return action.payload
-          .map((photo): ProcessingPhoto => ({ photo, state: 'preparing' }))
+          .map((photo): ProcessingPhoto => ({ photo, state: 'pending' }))
```
Comment (asutula) [inline App/features/photos/reducer.ts]: Photos are now added to the persistent redux state in a 'pending' state.

File: App/features/photos/sagas.ts [hunk 3]
```diff
@@ -22,16 +23,49 @@ function * toggleStorage(action: ActionType<typeof PreferencesActions.toggleStor
   }
 }
 
-function * nodeOnline() {
-  while (yield take([getType(TextileEventsActions.nodeOnline), getType(TextileEventsActions.stopNodeAfterDelayCancelled)])) {
+function * bootstrapPhotoProcessing() {
+  const QUEUE_CONCURRENT = 1
```
Comment (asutula) [inline App/features/photos/sagas.ts]: For now, processing one photo at a time.

File: App/features/photos/sagas.ts [hunk 4]
```diff
@@ -22,16 +23,49 @@ function * toggleStorage(action: ActionType<typeof PreferencesActions.toggleStor
...
+  const { watcher, addTaskChannel } = yield createQueue(photoHandler, QUEUE_CONCURRENT)
```
Comment (asutula) [inline App/features/photos/sagas.ts]: This creates our processing queue and workers, provides a channel to add new photo processing tasks to

File: App/features/photos/sagas.ts [hunk 5]
```diff
@@ -22,16 +23,49 @@ function * toggleStorage(action: ActionType<typeof PreferencesActions.toggleStor
...
+  yield fork(watcher)
+  yield call(processPending, addTaskChannel)
```
Comment (asutula) [inline App/features/photos/sagas.ts]: Before we allow any camera roll querying to happen, we want to add any still-pending photos to the queue first.

File: App/features/photos/sagas.ts [hunk 6]
```diff
@@ -22,16 +23,49 @@ function * toggleStorage(action: ActionType<typeof PreferencesActions.toggleStor
...
+  yield fork(queryForNewPhotos, addTaskChannel)
```
Comment (asutula) [inline App/features/photos/sagas.ts]: Then we fork off our saga that queries for new camera roll photos

File: App/features/photos/sagas.ts [hunk 7]
```diff
@@ -22,16 +23,49 @@ function * toggleStorage(action: ActionType<typeof PreferencesActions.toggleStor
...
+}
+
+function * photoHandler(payload: { id: string }) {
```
Comment (asutula) [inline App/features/photos/sagas.ts]: This is our pipeline for processing a single photo. It pauses until the node is online and then prepares, adds, and cleans up the photo.

File: App/features/photos/sagas.ts [hunk 8]
```diff
@@ -41,48 +75,40 @@ function * queryForNewPhotos() {
...
       yield put(actions.queryCameraRoll.success(results))
       yield put(actions.updateLastQueriedTime(currentRefresh))
-      for (const localPhotoResult of results) {
-        yield fork(preparePhoto, localPhotoResult.assetId)
-      }
+      yield all(
+        results.map((result) =>
+          put(addTaskChannel, { payload: { id: result.assetId } })
+        )
+      )
```
Comment (asutula) [inline App/features/photos/sagas.ts]: Here we now just add any new photo tasks to the queue instead of processing them directly

File: App/features/photos/sagas.ts [hunk 9]
```diff
@@ -136,11 +162,45 @@ function * watchForLoadPhotosRequests() {
   }
 }
 
+function* createQueue(handle: (...args: any[]) => IterableIterator<any>, concurrent = 1) {
```
Comment (asutula) [inline App/features/photos/sagas.ts]: Here's the fancy redux-saga code that created a concurrent queue/worker setup

File: App/screens/photos.tsx [hunk 10]
```diff
@@ -113,7 +113,8 @@ class Photos extends Component<Props> {
         />
       )
     } else {
-      const { photo, error } = row.item.processingPhoto
+      const { photo, state, error } = row.item.processingPhoto
+      const color = state === 'pending' ? 'white' : 'blue'
```
Comment (asutula) [inline App/screens/photos.tsx]: Display a white circle on `pending` photos, blue circle on photos that are currently being processed.

Comment (undercase) [inline App/screens/photos.tsx]: Considering that `color` is another style attribute used to change the font color, why not just directly call this variable `backgroundColor`.

Comment (asutula) [reply App/screens/photos.tsx]: Yea totally agree. This is temporary code that will be thrown out as soon as we make the real UI here, so wasn't worried too much about the nice details like that ;)
